---
sudo: false
language: python
python:
- '3.5'
addons:
  apt:
    packages:
    - libicu-dev
    - libxslt1-dev
    - libxml2-dev
    - pandoc
install: pip3 install -r requirements.txt
cache:
- pip
services:
- mongodb
script: nosetests --ignore-files='^\\.' --ignore-files='^setup\\.py$'
  --verbosity=3 --with-doctest scrapers
notifications:
  email: false
